#!/usr/bin/env python3
"""twoway_chips.py — the "reading …" lower-thirds, as a transparent overlay.

    python engine/twoway_chips.py <ep_number> [--pp DIR] [--out FILE]

🔴 WHY THIS FILE EXISTS. `twoway_composite.chips_for()` has generated the chips from
`episode.json` since the design was approved on 16 Sep — **and nothing ever drew them.**
The renderer written on 20 Sep does not mention `chips` anywhere, so three cuts shipped
without the one graphic that says who these two men are. Jodie, 20 Sep 2026: *"the
motion graphic overlay saying that Gordon is reading one person and Steve is reading
Barry Meadow, that's disappeared. I really liked that."*

📌 **BUILD SPEC A7 CALLS THEM THE ON-SCREEN HALF OF THE HONESTY RULE.** The spoken open
says Gordon is not Brian and Steve is not Barry; this is where a viewer who joins late
can see it. That is why they are not decoration and why their absence is a fault.

── HTML, NOT drawtext ────────────────────────────────────────────────────────────────
The design is a rounded card with a shadow, an orange rule, Anton at 52px over Barlow at
26px with one word in a heavier weight. `drawtext` can do none of that, and a chip that
approximates the design is a second design. So the chip is BUILT AS A PAGE, from
`chips_for()` and `layout.json`, and screenshotted on a transparent background — the
same way every other graphic on this channel is made.

⚠️ EVERY NUMBER AND EVERY WORD COMES FROM DATA. Nothing here types a name, a colour, a
size or a position: `chips_for()` supplies the content and the anchor, `layout.json`
supplies the type and the box. The one thing this file owns is the HTML.
"""
from __future__ import annotations

import argparse
import html
import json
import pathlib
import subprocess
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / ".claude/skills/pp-episode-production/scripts"))

import ep_paths                                                    # noqa: E402
import twoway_composite as tc                                      # noqa: E402

PP = pathlib.Path("G:/My Drive/PP Videos")
W, H = 1920, 1080


def page_html(chips: dict, layout: dict) -> str:
    """The two chips on a transparent 1920x1080 canvas, positioned by `chips_for`."""
    ch = layout["chips"]
    pad = ch["padding"]
    nm, rd, rule = ch["name"], ch["read"], ch["rule"]
    blocks = []
    for code, c in chips.items():
        blocks.append(f"""
  <div class="chip" style="left:{c['x']}px;bottom:{H - c['bottom_y']}px">
    <div class="rule" style="background:{c['rule_colour']}"></div>
    <div class="name">{html.escape(c['name'])}</div>
    <div class="read">reading <b>{html.escape(c['reading'])}</b></div>
    <div class="read role">{html.escape(c['role'])}</div>
  </div>""")
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>PP two-way chips</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Barlow:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<!-- PP-GENERATED by engine/twoway_chips.py from episode.json + layout.json.
     DO NOT HAND-EDIT: change the speakers or the layout, not this page. -->
<style>
html,body{{margin:0;padding:0;background:transparent}}
body{{width:{W}px;height:{H}px;overflow:hidden;font-family:'Barlow',sans-serif}}
.chip{{position:absolute;background:{ch['background']};border-radius:{ch['radius']}px;
  padding:{pad[0]}px {pad[1]}px {pad[2]}px {pad[3]}px;box-shadow:{ch['shadow']};
  display:inline-block}}
.rule{{width:{rule['w']}px;height:{rule['h']}px;margin-bottom:{rule['margin_bottom']}px}}
.name{{font-family:'Anton','Barlow',sans-serif;font-weight:400;
  font-size:{nm['size']}px;line-height:1.0;color:{nm['colour']};
  text-transform:{nm['transform']};letter-spacing:{nm['letter_spacing']}}}
.read{{font-size:{rd['size']}px;font-weight:{rd['weight']};
  line-height:{rd['line_height']};color:{rd['colour']};margin-top:{rd['margin_top']}px;
  white-space:nowrap}}
.read b{{color:{rd['emphasis_colour']};font-weight:{rd['emphasis_weight']}}}
.role{{margin-top:0}}
</style></head><body>{''.join(blocks)}
</body></html>"""


def render(ep: int, speaker: str, pp: pathlib.Path = PP,
           out: pathlib.Path | None = None) -> dict:
    d = ep_paths.episode_dir(ep, pp)
    epj = json.loads((d / "docs/episode.json").read_text(encoding="utf-8"))
    layout = tc.load_layout()
    chips = tc.chips_for(epj["speakers"], layout)

    # 🔴 THE RULE IS ORANGE ON THE MAN WHO IS TALKING AND GREY ON THE ONE LISTENING.
    # That is what `layout.chips.rule.colour` / `.listener_colour` mean, and the first
    # version of this file got it backwards by colouring the HOST orange regardless —
    # so the chips went out with Steve mid-sentence under a listener's grey rule and
    # Gordon silent under the speaker's orange. Caught by looking at the frame.
    #
    # 📌 It is a still, not an animation, because the chips are on screen for ONE
    # two-box run inside ONE turn: exactly one man is speaking for the whole of it, so
    # there is nothing to animate and nothing ambiguous to decide.
    if speaker not in chips:
        raise SystemExit(f"chips need to know who is speaking; got {speaker!r}, "
                         f"expected one of {sorted(chips)}")
    for code, c in chips.items():
        c["rule_colour"] = (c["rule_colour"] if code == speaker
                            else c["listener_rule_colour"])

    page = d / "overlay/export/twoway-chips.html"
    page.parent.mkdir(parents=True, exist_ok=True)
    page.write_text(page_html(chips, layout), encoding="utf-8")
    # the speaker is IN THE NAME: a chip drawn for the other man is a different file,
    # so a re-plan that changes who is talking cannot be served the old PNG.
    png = out or (d / f"overlay/export/twoway-chips-{speaker}.png")
    shot = HERE / "_shot_chips.py"
    shot.write_text(
        "import sys\n"
        "from playwright.sync_api import sync_playwright\n"
        "url, out = sys.argv[1], sys.argv[2]\n"
        "with sync_playwright() as p:\n"
        "    b = p.chromium.launch(headless=True, args=['--force-color-profile=srgb',"
        "'--disable-lcd-text','--hide-scrollbars','--force-device-scale-factor=1'])\n"
        f"    pg = b.new_page(viewport={{'width':{W},'height':{H}}}, "
        "device_scale_factor=1)\n"
        "    pg.goto(url, wait_until='load')\n"
        "    pg.wait_for_function(\"document.fonts.status === 'loaded'\", "
        "timeout=60000)\n"
        "    pg.screenshot(path=out, omit_background=True)\n"
        "    b.close()\n", encoding="utf-8")
    r = subprocess.run([sys.executable, str(shot), page.as_uri(), str(png)],
                       capture_output=True, text=True, timeout=600)
    if r.returncode or not png.is_file():
        raise SystemExit(f"chip render failed:\n{(r.stderr or '')[-1200:]}")
    return {"png": png, "html": page, "chips": chips,
            "visible_s": list(layout["chips"]["visible_s"])}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("ep_number", type=int)
    ap.add_argument("--pp", default=str(PP))
    ap.add_argument("speaker", help="the code of the man SPEAKING while they are up")
    ap.add_argument("--out")
    a = ap.parse_args()
    res = render(a.ep_number, a.speaker, pathlib.Path(a.pp),
                 pathlib.Path(a.out) if a.out else None)
    png = res["png"]
    print(f"wrote {png}  ({png.stat().st_size:,} bytes)")
    for code, c in res["chips"].items():
        print(f"  {code}: {c['name']} / reading {c['reading']} / {c['role']}  "
              f"at ({c['x']}, bottom {c['bottom_y']})  rule {c['rule_colour']}")
    print(f"  visible {res['visible_s'][0]}-{res['visible_s'][1]}s of dialogue")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
