#!/usr/bin/env python3
"""author_cards.py — author motion-graphic card pages by PURE SUBSTITUTION.

    python author_cards.py <episode.json> <out_dir> [--only C1,C2] [--force]

THE ONE PROPERTY THIS SCRIPT MUST HAVE
--------------------------------------
It is structurally incapable of emitting visible text that is not already in
`episode.json`. There is no LLM in it, no inference, no defaulting-to-a-phrase,
no string built from anything but (a) template literals and (b) values copied
out of `cards[].content`. If a value is missing it HALTS; it never fills a gap.

That is guard 3 of DESIGN-self-authoring-build.md §6, and it is a capability the
program does not have rather than a rule it is asked to follow.

THE OTHER TWO GUARDS
--------------------
1. SCHEMA VALIDATION before anything renders. Unknown block, unknown key for
   that block, missing required key, wrong list length -> halt naming card+key.
2. TRACE-OR-HALT. Any content value containing a digit needs a `trace` entry,
   that entry must be a literal substring of the source article, AND every
   digit-run in the value must appear inside the traced sentence. The second
   half is what catches EP11's C7: the traced sentence was real, but it did not
   contain the "2nd"/"3rd" placings that had been inferred from listing order.

EXPLICIT null RENDERS AN EMPTY SLOT. A MISSING KEY HALTS.
That is the EP12 `_placeholder` lesson: explicit null says a human decided this
is empty; absence says nobody decided.

NEVER OVERWRITE HAND-AUTHORED WORK. Generated pages carry the marker comment
below. A page without it is treated as hand-authored and left alone; `block:
"bespoke"` is never generated at all.
"""
import argparse
import html
import json
import os
import re
import sys
import unicodedata

for _s in (sys.stdout, sys.stderr):       # the Windows console is cp1252
    try:
        _s.reconfigure(encoding="utf-8")
    except Exception:                     # noqa: BLE001
        pass

HERE = os.path.dirname(os.path.abspath(__file__))
CARDS_DIR = os.path.join(os.path.dirname(HERE), "assets", "cards")
if HERE not in sys.path:
    sys.path.insert(0, HERE)

# 🔴 ONE Halt CLASS, IMPORTED RATHER THAN REDECLARED. `card_lift` raises the same
# exception this module raises, so `except Halt` in main() — and `except ac.Halt`
# in every caller — catches a lift fault exactly as it catches a schema fault. Two
# classes with the same name is the one-value-in-two-places fault wearing a
# traceback: the second one is caught by nothing and reaches a human as a crash.
from card_lift import Halt, apply_lifts        # noqa: E402,F401  (re-exported)
import card_lift                               # noqa: E402

MARKER = "<!-- PP-GENERATED by author_cards.py — DO NOT HAND-EDIT. "\
         "To change this card, change episode.json; to take it over by hand, "\
         "set block:\"bespoke\" and delete this line. -->"

# Inline markup a content value is allowed to carry. Everything else is escaped,
# so episode.json cannot inject script, style or structure into a card.
INLINE_OK = ("<b>", "</b>", "<br>")


# ---------------------------------------------------------------- templates

SECTIONS = ("schema", "css", "print", "markup", "anim")


def _sections(text):
    """Split a block file on its section markers.

    A marker is `<!--@name-->` on its own line, or `<!--@name` opening a
    multi-line HTML comment (the schema is JSON, so it is written that way and
    closed by a line that is just `-->`).
    """
    out, name, buf = {}, None, []
    for line in text.splitlines():
        m = re.match(r"\s*<!--@(\w+)\s*(?:-->)?\s*$", line)
        if m and m.group(1) in SECTIONS:
            if name:
                out[name] = "\n".join(buf).strip("\n")
            name, buf = m.group(1), []
            continue
        if line.strip() == "-->" and name == "schema":
            continue
        if name:
            buf.append(line)
    if name:
        out[name] = "\n".join(buf).strip("\n")
    return out


def load_block(block):
    path = os.path.join(CARDS_DIR, "blocks", block + ".html")
    if not os.path.exists(path):
        have = sorted(f[:-5] for f in os.listdir(os.path.join(CARDS_DIR, "blocks"))
                      if f.endswith(".html"))
        raise Halt(f"unknown block {block!r}. Known blocks: {', '.join(have)}")
    s = _sections(open(path, encoding="utf-8").read())
    for need in ("schema", "markup", "anim"):
        if need not in s:
            raise Halt(f"block {block!r} template is missing its @{need} section")
    s["schema"] = json.loads(s["schema"])
    return s


def load_frame(layout):
    path = os.path.join(CARDS_DIR, f"frame-{ 'panel' if layout == 'panel-push' else 'fullscreen' }.html")
    if not os.path.exists(path):
        raise Halt(f"no frame template for layout {layout!r} (expected {path})")
    return open(path, encoding="utf-8").read()


# ---------------------------------------------------------------- normalising

_QUOTES = {"‘": "'", "’": "'", "“": '"', "”": '"',
           "–": "-", "—": "-", "−": "-", " ": " "}


def norm(s):
    """Normalise for the TRACE comparison only — never for what is rendered.

    Whitespace is collapsed and typographic quotes/dashes are folded to ASCII.
    The design said "whitespace only"; quotes had to be added because the cards
    carry curly quotes and the source articles carry straight ones, so a
    whitespace-only comparison failed every single trace. Widening this further
    (case, punctuation, stemming) would start hiding real mismatches.
    """
    s = unicodedata.normalize("NFKC", s)
    s = "".join(_QUOTES.get(ch, ch) for ch in s)
    return re.sub(r"\s+", " ", s).strip()


def digit_runs(s):
    return re.findall(r"\d+(?:\.\d+)?", s)


# A figure a viewer can READ is not always a digit. EP17 C3 captions its bars
# "Sixteen per cent" / "Ten per cent" / "Five per cent" — the strike rates, spelled
# out, which is a figure on the screen by any reading of the word. See
# assert_measured_items_show_a_figure for what this is used for and what it costs.
NUMBER_WORDS = (
    "zero one two three four five six seven eight nine ten eleven twelve thirteen "
    "fourteen fifteen sixteen seventeen eighteen nineteen twenty thirty forty fifty "
    "sixty seventy eighty ninety hundred thousand million billion"
).split()
NUMBER_WORD_RE = re.compile(r"\b(" + "|".join(NUMBER_WORDS) + r")\b", re.I)


def shows_a_figure(s):
    """Does this string put a quantity in front of a viewer — in digits OR in words?"""
    return bool(re.search(r"\d", s) or NUMBER_WORD_RE.search(s))


# ---------------------------------------------------------------- validation

def validate(card, blk):
    """Halt on anything the schema does not describe. Returns nothing."""
    cid = card.get("id", "<no id>")
    schema = blk["schema"]
    content = card.get("content")
    if content is None:
        raise Halt(f"card {cid}: block {card['block']!r} needs a content{{}} object and there is none")
    if not isinstance(content, dict):
        raise Halt(f"card {cid}: content must be an object, got {type(content).__name__}")

    required = schema.get("required", [])
    optional = schema.get("optional", [])
    lists = schema.get("lists", {})
    known = set(required) | set(optional) | set(lists)

    for k in content:
        if k not in known:
            raise Halt(f"card {cid}: unknown key {k!r} for block {card['block']!r}. "
                       f"This block accepts: {', '.join(sorted(known))}")
    # EVERY key the block declares must be PRESENT. Required keys must also be
    # non-null. An optional key may be null — that renders an empty slot, and it
    # records that a human decided it is empty. Absence records nothing, so it halts.
    for k in required + optional:
        if k not in content:
            kind = "required" if k in required else "optional"
            raise Halt(f"card {cid}: MISSING {kind} key {k!r} for block {card['block']!r}. "
                       f"If the value is deliberately empty write null — a missing key halts "
                       f"on purpose, because absence means nobody decided.")
    for k in required:
        if content[k] is None:
            raise Halt(f"card {cid}: key {k!r} is null, but block {card['block']!r} requires "
                       f"a value for it.")
    for name, spec in lists.items():
        if name not in content:
            if name in required:
                raise Halt(f"card {cid}: MISSING required list {name!r}")
            continue
        items = content[name]
        if not isinstance(items, list):
            raise Halt(f"card {cid}: {name!r} must be a list")
        lo, hi = spec.get("min", 1), spec.get("max", 99)
        if not (lo <= len(items) <= hi):
            raise Halt(f"card {cid}: {name!r} has {len(items)} items; block {card['block']!r} "
                       f"takes between {lo} and {hi}")
        fields = spec.get("fields")
        for i, it in enumerate(items, 1):
            if fields is None:
                if it is not None and not isinstance(it, str):
                    raise Halt(f"card {cid}: {name}[{i}] must be a string or null")
            else:
                if not isinstance(it, dict):
                    raise Halt(f"card {cid}: {name}[{i}] must be an object with {fields}")
                for k in it:
                    if k not in fields:
                        raise Halt(f"card {cid}: {name}[{i}] has unknown field {k!r}; allowed: {fields}")
                for k in fields:
                    if k not in it:
                        raise Halt(f"card {cid}: {name}[{i}] is MISSING field {k!r}. "
                                   f"Write null for a deliberately empty slot.")
                # Fields that select a style variant are a closed set, so a content
                # value can never invent a CSS class.
                for k, allowed_vals in spec.get("enum", {}).items():
                    if it.get(k) not in allowed_vals:
                        raise Halt(f"card {cid}: {name}[{i}].{k} = {it.get(k)!r} is not one of "
                                   f"{allowed_vals}. This field picks a style variant, "
                                   f"so it is a closed set.")
                # Fields that drive a measurement must be bare numbers.
                for k in spec.get("numeric", []):
                    if not re.match(r"^\d+(\.\d+)?$", str(it.get(k, ""))):
                        raise Halt(f"card {cid}: {name}[{i}].{k} = {it.get(k)!r} must be a bare "
                                   f"number — it sets a bar length, not a caption.")
                # A field that is ITSELF A LIST — the cells of a row.
                cs = spec.get("cells")
                if cs:
                    cells = it.get(cs["field"])
                    if not isinstance(cells, list):
                        raise Halt(f"card {cid}: {name}[{i}].{cs['field']} must be a list "
                                   f"of cell values, got {type(cells).__name__}")
                    for j, cell in enumerate(cells, 1):
                        if cell is not None and not isinstance(cell, str):
                            raise Halt(f"card {cid}: {name}[{i}].{cs['field']}[{j}] must be "
                                       f"a string or null")

    # ── A GRID WHOSE ROWS AND COLUMNS DISAGREE IS A GRID THAT LIES ──────────────
    # The one integrity rule a matrix has, and the reason it is worth a block rather
    # than a hand-authored page. EP19 C12's own note says why: with three columns by
    # three rows, "a viewer could not tell which figure belongs to which run" if the
    # axes stop lining up. A row one cell short does not look broken — it looks like a
    # different, wrong answer, silently shifted a column to the left.
    grid = schema.get("grid")
    if grid:
        cols = content.get(grid["columns"]) or []
        for i, row in enumerate(content.get(grid["rows"]) or [], 1):
            cells = (row or {}).get(grid["cells"]) or []
            if len(cells) != len(cols):
                raise Halt(
                    f"card {cid}: row {i} ({(row or {}).get('label')!r}) has {len(cells)} "
                    f"cell(s) but there are {len(cols)} columns "
                    f"({', '.join(map(str, cols))}). Every row must line up with every "
                    f"column: a short row does not look broken on the card, it silently "
                    f"shifts every value one column to the left and states something the "
                    f"article never said. Write null for a deliberately empty cell.")


def walk_values(content):
    """Yield (dotted_key, value) for every leaf string in content.

    🔴 IT RECURSES INTO A LIST INSIDE AN ITEM, and it must. `matrix` holds
    rows[].cells[] — the grid's actual numbers — and without this every one of them
    would be yielded as a LIST, which check_trace skips (`not isinstance(val, str)`)
    and assert_measured_items_show_a_figure never sees. The block would have shipped
    nine untraced figures on a card whose entire purpose is nine figures, and every
    gate would have said yes. Found while building the block, not after.
    """
    for k, v in content.items():
        if isinstance(v, list):
            for i, it in enumerate(v, 1):
                if isinstance(it, dict):
                    for kk, vv in it.items():
                        if isinstance(vv, list):
                            for j, cell in enumerate(vv, 1):
                                yield f"{k}[{i}].{kk}[{j}]", cell
                        else:
                            yield f"{k}[{i}].{kk}", vv
                else:
                    yield f"{k}[{i}]", it
        else:
            yield k, v


JOBS = ("orient", "locate", "relate", "anchor")

# R3a — a job is a CLAIM, and a claim needs a check.
#
# Assertion fell from 54% to 20% overnight and the pictures were IDENTICAL: the
# cards had been RELABELLED, not changed. A `statement` block declaring itself
# `relate` makes the metric improve while the episode does not — which is the
# oldest way there is to pass a gate without doing the work. So the declared job
# must be consistent with the block that actually renders: a card cannot claim to
# relate two things using a block that can only assert one.
JOB_BLOCKS = {
    # `statement` is here on the standard's OWN wording: R3 counts pure assertion as
    # "anchor, or a bare statement". A bare statement IS an assertion, so it must
    # declare `anchor` and be counted against the 40% cap — not hide under `relate`.
    "anchor": {"stat", "price", "statement"},
    # `slate` and `checklist` CONFIRMED for relate by Jodie, 29 Jul 2026: "four causes
    # pointing at one outcome IS a relationship, and C3's two lists of what stands
    # between ability and result is the same shape." SUBJECT TO THE LIST QUALIFIER
    # below — a list earns `relate` only when it shows what the items connect TO.
    # `matrix` is the most relating block there is: it states every row AGAINST every
    # column, and the relationship IS the card — a form-points grid says nine things
    # about how placing and recency combine, none of which survives being listed.
    # `ladder` is a relating block by construction: it draws five to seven anchor rows
    # AGAINST each other so the trend is the picture — short odds eat your book, long
    # odds barely dent it — and no single row of it says that.
    "relate": {"compare", "steps", "bars", "ratio", "slate", "checklist", "matrix",
               "ladder"},
    "orient": {"steps", "slate"},
    # `locate` is the rail modifier — it rides on any block, so it constrains none.
    "locate": None,
}

# Blocks that merely ENUMERATE. They can relate — but only by naming the thing the
# items connect to (see the list qualifier in check_job).
LIST_BLOCKS = {"checklist", "slate"}

# R3 IS MEASURED ON THE BLOCK, NEVER ON THE DECLARED JOB. Assertion "fell" from 54%
# to 20% overnight while the pictures stayed identical, because the cards had been
# relabelled. A metric you can move by editing a label is not a metric.
ASSERTION_BLOCKS = {"stat", "price", "statement"}
MAX_ASSERTION = 0.40


def check_mix(cards):
    """R3: at most 40% of content cards may be pure assertion, counted BY BLOCK."""
    content = [c for c in cards if c.get("block") and c.get("page")]
    if not content:
        return []
    hard = [c["id"] for c in content if c["block"] in ASSERTION_BLOCKS]
    share = len(hard) / len(content)
    if share > MAX_ASSERTION:
        return [f"EPISODE MIX: {len(hard)} of {len(content)} content cards are pure assertion "
                f"({share*100:.0f}%), over the {MAX_ASSERTION*100:.0f}% cap "
                f"(pp-visual-standard R3). The assertion cards are {hard}. Measured on the "
                f"BLOCK, not the declared job — relabelling does not change a picture."]
    return []


def check_job(card):
    """R2 of the visual standard: EVERY CARD DECLARES ITS JOB. No job, no build.

    The four jobs are orient / locate / relate / anchor, and they are the answer to
    "what is this card FOR". A card that does none of them is decoration — and
    decoration is not free: the coherence principle says it makes the episode
    WORSE, not merely no better. The vocabulary is owned by the pp-visual-standard
    skill; this is only the gate.

    It is a closed list on purpose, exactly like `ebook.departures` and the block
    names: a free-text field would let "job": "explain" through, and the whole
    point is that the author must pick one of four and live with it.
    """
    j = card.get("job")
    if j is None:
        return [f"card {card.get('id', '?')}: MISSING 'job'. Every card must declare what it is "
                f"FOR — one of {', '.join(JOBS)} (pp-visual-standard R2). A card that does none "
                f"of the four is decoration and must not be built."]
    if j not in JOBS:
        return [f"card {card.get('id', '?')}: job {j!r} is not one of {', '.join(JOBS)}. "
                f"This is a closed vocabulary, not free text."]
    allowed = JOB_BLOCKS.get(j)
    blk = card.get("block")
    if allowed is not None and blk not in allowed and blk != "bespoke":
        return [f"card {card.get('id', '?')}: declares job {j!r} but uses block {blk!r}. "
                f"{j!r} needs one of {sorted(allowed)} (pp-visual-standard R3a). A job is a "
                f"CLAIM about what the card does — relabelling a block does not change the "
                f"picture, and R3 is measured on the BLOCK for exactly that reason."]
    # THE LIST QUALIFIER (Jodie, 29 Jul 2026). A list block earns `relate` only when it
    # shows what the items connect TO. "These four things set the track bias" is a
    # relationship — many causes, one outcome. A bare enumeration with no subject is
    # assertion wearing a list's clothes, and it must declare `anchor` and count
    # against the 40% cap instead. The connection has to be NAMED, so the claim is
    # explicit and reviewable rather than implied by the choice of block.
    if j == "relate" and blk in LIST_BLOCKS and not str(card.get("relates_to") or "").strip():
        return [f"card {card.get('id', '?')}: a {blk!r} claiming job 'relate' must name what "
                f"its items connect to, in 'relates_to' (pp-visual-standard R3a, the list "
                f"qualifier). Many causes pointing at ONE outcome is a relationship; a bare "
                f"enumeration is assertion wearing a list's clothes — declare 'anchor' for "
                f"that and let it count against the 40% cap."]
    return []


def check_trace(card, article_norm):
    """Trace-or-halt. Any value with a digit must be traceable to the article."""
    cid = card.get("id", "<no id>")
    trace = card.get("trace") or {}
    problems = []
    # The headline and the eyebrow are figures too. EP12 C3's headline IS the
    # claim ("90 Days Is Not 180 Days") and EP11 C4's eyebrow carries a date;
    # checking only content{} would leave the largest text on the card untraced.
    extra = [("headline", card.get("headline_display") or card.get("headline")),
             ("eyebrow", card.get("eyebrow"))]
    # The rail prints "Rule N of M". M is a claim about the article — how many rules
    # there are — so it is a figure and must trace like any other. N is not a claim
    # about the world, it is a pointer into the list this very card displays, so it is
    # bounds-checked and cross-checked against the eyebrow in apply_rail() instead.
    rail = card.get("rail") or {}
    if rail.get("of") is not None:
        extra.append(("rail", str(rail["of"])))
    # 🔵 A LIFTED VALUE HAS BETTER PROVENANCE THAN A TRACED ONE, and this is the only
    # place that is true. A trace is a writer QUOTING the article and a checker
    # confirming the quote; a lift is the article READ BY A PROGRAM, cell by cell,
    # asserted before a byte is written (card_lift.py). Demanding a trace sentence for
    # a figure nobody typed would be asking the writer to quote a sentence for a
    # number they never saw — and the only way to satisfy it would be to go and find
    # one, which is the transcription this exists to remove.
    #     🔒 IT IS EXACT AND IT IS NARROW: only the lists card_lift actually filled and
    # the key it asserted the row-count into. Everything else on a lifted card — the
    # eyebrow, the headline, a typed note beside the chart — traces exactly as before.
    # The proof of the narrowing is in test_card_lift: a typed figure in the eyebrow of
    # a lifted card is still reported.
    lifted_lists = card_lift.lifted_lists(card)
    lifted_keys = card_lift.lifted_keys(card)
    for key, val in list(walk_values(card["content"])) + extra:
        if not isinstance(val, str) or not re.search(r"\d", val):
            continue
        base = key.split("[")[0]
        if base in lifted_lists or key in lifted_keys:
            continue
        sentence = trace.get(key, trace.get(base))
        if sentence is None:
            problems.append(f"{cid}.{key} = {val!r} carries a figure and has NO trace entry. "
                            f"Add trace[{base!r}] quoting the source sentence.")
            continue
        sn = norm(sentence)
        if sn not in article_norm:
            problems.append(f"{cid}.trace[{base!r}] is not a literal substring of the source "
                            f"article: {sentence!r}")
            continue
        missing = [d for d in digit_runs(norm(val)) if d not in sn]
        if missing:
            problems.append(
                f"{cid}.{key} = {val!r} shows figure(s) {missing} that do NOT appear in its own "
                f"traced sentence. The sentence is real but it does not say this. "
                f"(This is the EP11 C7 failure: placings inferred from listing order.)")
    return problems


ODDS = re.compile(r"\b\d{1,3}\s*/\s*\d{1,3}\b")
MONEY = re.compile(r"\$\s?\d")


def check_converted_odds(card):
    """A card may not show a price the ARTICLE gave as a conversion of its own odds.

    🔒 JODIE, 9 AUG 2026, ON EP19 C8. The card read "$1.75 to $3.25" over the caption
    "in tote terms", and the quote read "at least 4/1 ($5)". Every one of those dollar
    figures is the article's own parenthetical gloss on its fractional odds:

        "Look at pre-post favourites with odds in the range 8/11 to 9/4 inclusive
         (that is, in tote terms, $1.75 to $3.25).The second-favourite must be at
         least 4/1 ($5)."

    The conversion never appears. A 2004 UK fraction restated as a tote dollar price is
    a number the viewer cannot check against anything they will meet today, and it puts
    a figure on screen that the source is only estimating. The card carries the rule the
    way the article states it — in fractions — and the trace keeps the whole sentence,
    parenthetical and all, because a trace is provenance and not words on a card.

    ⚠️ WHY A GUARD AND NOT A LINE IN THE BRIEF. The prohibition already existed and
    already worked: EP19's spoken script contains no dollar price anywhere. It reached
    the SCRIPT commission and never reached the CARD commission, so the one surface
    nobody re-read shipped the thing the rule forbids. A rule that lives in a prompt
    protects whichever asset the prompt is for; this one now fails the build.

    THE TEST IS THE TRACE, not a word list. A dollar amount is perfectly fine — a bank,
    a stake, a season's profit. What is forbidden is a dollar amount whose OWN traced
    sentence states the same thing in odds, because that is what a conversion IS.

    ⚠️ AND A CONVERSION HAS A DIRECTION (11 Aug 2026). "Odds present in the sentence"
    was too coarse and it fired on EP18 C4, an episode that shipped and is right:

        "favourites had an average dividend of $2.80 (about 7/4) but showed a
         dramatic 25 per cent loss on turnover"

    There the DOLLAR is the article's own figure and the ODDS are its parenthetical
    gloss — the exact mirror of EP19 C8's "8/11 to 9/4 inclusive (that is, in tote
    terms, $1.75 to $3.25)". The card must carry whichever the article states in its
    OWN VOICE, and the gloss is what stays behind. So the test is now WHERE the money
    sits: a dollar figure the sentence states outside its brackets is the article's,
    and one that appears only inside them is the conversion. Found by running this
    check over every shipped episode before wiring it into the commission — a wrong
    halt there costs three repair cycles, not one line in a run log.
    """
    cid = card.get("id", "<no id>")
    trace = card.get("trace") or {}
    problems = []
    for key, val in walk_values(card["content"]):
        if not isinstance(val, str) or not MONEY.search(val):
            continue
        sentence = trace.get(key, trace.get(key.split("[")[0])) or ""
        if not ODDS.search(sentence):
            continue                 # a price the article states as a price: fine
        # The sentence with every parenthetical removed = what the article says in
        # its own voice. A figure surviving there was never a gloss on anything.
        plain = re.sub(r"\([^)]*\)", " ", sentence)
        mine = digit_runs(val.replace(",", ""))
        if any(d in plain.replace(",", "") for d in mine):
            continue                 # the article's OWN dollar figure — EP18 C4
        problems.append(
            f"{cid}.{key} = {val!r} shows a DOLLAR price, and its own traced sentence "
            f"states that figure as ODDS: {sentence.strip()[:120]!r}. That makes this "
            f"the article's tote conversion, which never goes on a card. Put the "
            f"article's own fractional odds in the content — the trace can keep the "
            f"whole sentence, conversion and all, because a trace is provenance and "
            f"not words a viewer reads.")
    return problems


def check_dead_trace(card):
    """A trace key that matches NO content key is a dead citation. (E-b)

    🔴 A DEAD CITATION LOOKS EXACTLY LIKE A LIVE ONE. Nothing reads it, nothing
    reports it, and the value it was written for silently falls back to the list's
    general entry — or to nothing at all.

    EP18, 8 Aug 2026: every per-item key in that file was written 0-BASED while
    `walk_values` yields 1-BASED (`enumerate(v, 1)`). All nine entries were
    therefore addressed to the row BELOW the one they were written for, and the
    last row of each list had no entry at all. It surfaced as EIGHT trace faults
    across five cards; it was ONE fault, and this check names it directly.

    The valid set is DERIVED from `walk_values` — the same function `check_trace`
    uses to decide what needs a citation — so it cannot drift from it.
    """
    cid = card.get("id", "<no id>")
    trace = card.get("trace") or {}
    content = card.get("content")
    if not trace or not isinstance(content, dict):
        return []
    live, bases, counts = set(), set(), {}
    for key, _v in walk_values(content):
        live.add(key)
        b = key.split("[")[0]
        bases.add(b)
        live.add(b)
        m = re.match(r"^[A-Za-z_]+\[(\d+)\]", key)
        if m:
            counts[b] = max(counts.get(b, 0), int(m.group(1)))
    live |= {"headline", "eyebrow", "rail"}
    problems = []
    for k in sorted(trace):
        if k in live:
            continue
        b = k.split("[")[0]
        m = re.match(r"^[A-Za-z_]+\[(\d+)\]", k)
        # ⚠️ ONLY INDEX-SHAPED DEAD KEYS HALT, and the narrowing is deliberate.
        # A key like `bars[0].value` is a MISADDRESSED CITATION: the list is real, so
        # the entry was written for a row and silently landed on a different one (or on
        # none). That is EP18's fault and it is dangerous.
        # A key that matches nothing at all — EP16 c02 carries `trace["Three chances"]`
        # — is untidy, reads as a note, and misleads nobody. Halting on it would have
        # blocked EP16, an episode that shipped fine, which is the "guard that halts a
        # good episode is the version somebody switches off" failure (CLAUDE.md 4a).
        # Those are returned by check_stray_trace() as WARNINGS instead.
        if not (m and b in bases):
            continue
        i, n = int(m.group(1)), counts.get(b, 0)
        why = (f"{b!r} is indexed from 1 and has {n} item(s), so the valid keys are "
               f"{b}[1] to {b}[{n}]." + (" A 0-based key is the usual cause — the "
               "citation then lands on the row below the one it was written for."
               if i == 0 else ""))
        problems.append(f"{cid}.trace[{k!r}] matches no value on this card — {why}")
    return problems


def check_stray_trace(card):
    """Trace keys that address nothing recognisable — untidy, reported, never fatal.

    The sibling of check_dead_trace: same derivation, opposite severity. See the
    comment there for why the split exists.
    """
    cid = card.get("id", "<no id>")
    trace = card.get("trace") or {}
    content = card.get("content")
    if not trace or not isinstance(content, dict):
        return []
    live, bases = set(), set()
    for key, _v in walk_values(content):
        live.add(key)
        bases.add(key.split("[")[0])
        live.add(key.split("[")[0])
    live |= {"headline", "eyebrow", "rail"}
    out = []
    for k in sorted(trace):
        if k in live:
            continue
        if re.match(r"^[A-Za-z_]+\[(\d+)\]", k) and k.split("[")[0] in bases:
            continue                      # that one is a blocker, handled above
        out.append(f"{cid}.trace[{k!r}] addresses nothing on this card and is never read. "
                   f"Harmless, but it looks like a citation and is not one. "
                   f"Content keys here: {sorted(bases | (set(content) - bases)) or 'none'}.")
    return out


# ---------------------------------------------------------------- rendering

def esc(v):
    """Escape a content value, then re-admit the small inline whitelist.

    This is the choke point that makes fabrication structurally impossible:
    every visible character in a generated card comes through here from
    episode.json, or is a literal in the template file.
    """
    if v is None:
        return ""
    if not isinstance(v, str):
        raise Halt(f"content values must be strings or null, got {type(v).__name__}: {v!r}")
    out = html.escape(v, quote=False)
    for tag in INLINE_OK:
        out = out.replace(html.escape(tag, quote=False), tag)
    return out


EACH_OPEN = re.compile(r"<!--@each ([\w.]+)-->")
EACH_CLOSE = "<!--@endeach-->"


def _first_each(tpl):
    """The first TOP-LEVEL each region: (before, name, body, after), or None.

    🔴 DEPTH-COUNTED, NOT A NON-GREEDY REGEX, and that is the whole reason a matrix
    could not be templated before. The old expansion was
    `re.sub(r"<!--@each (\\w+)-->(.*?)<!--@endeach-->", …)`: with one loop inside
    another, `(.*?)` stops at the INNER `<!--@endeach-->`, so the outer region ends in
    the middle of itself and the leftover close tag lands in the page. A grid is rows
    each holding cells — nesting is not an exotic case, it is the shape of the thing —
    and this is why EP15 C12 and EP19 C12 were both hand-authored instead.
    """
    m = EACH_OPEN.search(tpl)
    if not m:
        return None
    depth, pos, close_at = 1, m.end(), None
    while depth:
        nxt_open = EACH_OPEN.search(tpl, pos)
        nxt_close = tpl.find(EACH_CLOSE, pos)
        if nxt_close < 0:
            raise Halt(f"template has <!--@each {m.group(1)}--> with no matching "
                       f"<!--@endeach-->")
        if nxt_open and nxt_open.start() < nxt_close:
            depth += 1
            pos = nxt_open.end()
        else:
            depth -= 1
            close_at, pos = nxt_close, nxt_close + len(EACH_CLOSE)
    return tpl[:m.start()], m.group(1), tpl[m.end():close_at], tpl[pos:]


def expand_each(tpl, content, blk, anim=False, anim_over=None):
    """Expand <!--@each name--> ... <!--@endeach--> regions.

    {{ITEM}} / {{ITEM.field}} — the value, escaped
    {{I}}                     — 1-based index (element ids, never visible text)
    {{DELAY}}                 — stagger delay from the block's declared base+step
    {{WIDTH}}                 — a length in px PROPORTIONAL to the item's numeric
                                field, so a bar cannot misstate the ratio it draws

    NESTED: inside an item, `<!--@each ITEM.field-->` walks a LIST held by that item —
    the cells of a row. Its body uses {{CELL}} and {{J}} (1-based). The names are
    deliberately different from {{ITEM}} and {{I}} rather than shadowing them: a
    template where the same token means the row in one line and the cell in the next
    is a template nobody can read, and this one draws a grid where getting the column
    wrong misstates which figure belongs to which run.
    """
    lists = blk["schema"].get("lists", {})
    anim_spec = blk["schema"].get("anim", {}) if anim else {}
    # ⚠️ A LONGER LIST NEEDS A FASTER STAGGER, or it is still arriving when the
    # card leaves. `checklist` staggers 550ms an item: fine for six (3.9s), and
    # for TWELVE it means the last item appears at 7.2s on a card held ten. The
    # reflow rung that widened the card to two columns lowers the step to match,
    # so the whole list is on screen in about the same time it always was. Only
    # the rung a card actually lands on is applied, so a six-item card keeps the
    # exact timing it has always had.
    if anim and anim_over:
        anim_spec = dict(anim_spec)
        anim_spec.update(anim_over)

    def one(name, body):
        items = content.get(name)
        if items is None:
            return ""
        spec = lists.get(name, {})
        step = anim_spec.get(name, {})
        scale = spec.get("scale")
        span = 0.0
        if scale:
            vals = [float(it[scale["field"]]) for it in items]
            span = max(vals) or 1.0
        chunks = []
        for i, it in enumerate(items, 1):
            piece = body
            # THE ITEM'S OWN LISTS FIRST, while `it` is in scope. Walking the region
            # again afterwards would have lost which row each cell belongs to.
            while True:
                found = _first_each(piece)
                if not found or not found[1].startswith("ITEM."):
                    break
                pre, iname, ibody, post = found
                cells = (it or {}).get(iname.split(".", 1)[1]) if isinstance(it, dict) else None
                out = []
                for j, cell in enumerate(cells or [], 1):
                    c = ibody
                    if isinstance(cell, dict):
                        for k, v in cell.items():
                            c = c.replace("{{CELL." + k + "}}", esc(v))
                    else:
                        c = c.replace("{{CELL}}", esc(cell))
                    out.append(c.replace("{{J}}", str(j)))
                piece = pre + "".join(out) + post
            if isinstance(it, dict):
                for k, v in it.items():
                    if isinstance(v, (list, dict)):
                        continue            # a nested list is drawn by its own each
                    piece = piece.replace("{{ITEM." + k + "}}", esc(v))
                if scale:
                    w = round(float(it[scale["field"]]) / span * scale["span"])
                    piece = piece.replace("{{WIDTH}}", str(w))
            else:
                piece = piece.replace("{{ITEM}}", esc(it))
            piece = piece.replace("{{I}}", str(i))
            if step:
                piece = piece.replace("{{DELAY}}", str(step["base"] + (i - 1) * step["step"]))
                if "base2" in step:
                    piece = piece.replace("{{DELAY2}}",
                                          str(step["base2"] + (i - 1) * step["step2"]))
            chunks.append(piece)
        return "".join(chunks)

    out, rest = [], tpl
    while True:
        found = _first_each(rest)
        if not found:
            out.append(rest)
            break
        before, name, body, after = found
        out.append(before)
        out.append(one(name, body))
        rest = after
    return "".join(out)


# An element whose WHOLE body is one placeholder. Nothing else can match: the
# per-item tokens ({{ITEM}}, {{CELL}}, {{I}}) are gone by the time fill() runs,
# because expand_each has already replaced them.
BARE_SLOT = re.compile(r"<(\w+)(?:\s[^>]*)?>\s*\{\{(\w+)\}\}\s*</\1>")


def fill(tpl, content):
    """Replace {{key}} with the escaped content value. Unresolved token = halt.

    🔴 AN EMPTY SLOT MUST NOT DRAW A BOX (11 Aug 2026, EP20 C5). `null` renders an
    empty string, which is right for a line of text and WRONG for a decorated one:
    `bars` ends with `<div class="chip">{{chip}}</div>` and .chip is a pill with a
    background, a border and 14px of padding. With `chip: null` the finished card
    showed a small empty grey lozenge in the bottom-left corner — a thing on screen
    that nobody wrote, which is the fabrication rule from the other direction.

    IT WAS NEVER SEEN BECAUSE EVERY EARLIER `bars` CARD HAD THREE BARS and the pill
    was pushed off the bottom edge. EP20's has two, so it landed in shot. That is the
    shape of this whole class: not a new fault, a fault whose first VISIBLE instance
    happened to be episode twenty.

    The rule is derived, not a list of class names: an element whose entire body is
    one placeholder has nothing to show when that placeholder is null, so it is
    removed rather than emptied. It cannot touch a `bars` bar or a `ratio` column —
    those carry no placeholder and ARE the picture. pp-anim.js skips a selector that
    matches nothing (`if (el)`), and ppDuration is computed from the spec rather than
    from the elements, so clip lengths do not move.
    """
    def one(m):
        k = m.group(1)
        if k not in content:
            raise Halt(f"template wants {{{{{k}}}}} but content has no key {k!r}")
        return esc(content[k])
    tpl = BARE_SLOT.sub(lambda m: "" if content.get(m.group(2), "") is None
                        else m.group(0), tpl)
    out = re.sub(r"\{\{(\w+)\}\}", one, tpl)
    leftover = re.findall(r"\{\{[\w.]+\}\}", out)
    if leftover:
        raise Halt(f"template left unresolved placeholders: {sorted(set(leftover))}")
    return out


FIT_NUM = re.compile(r"^-?\d+(\.\d+)?(px|em|%)?$")

# Fit keys shared by both frames. Numeric only — no text can enter through fit.
FRAME_FIT = {
    "headline_size":      (".hl", "font-size"),
    "headline_leading":   (".hl", "line-height"),
    "headline_top":       (".hl", "margin-top"),
    "eyebrow_size":       (".eyebrow .lbl", "font-size"),
    "eyebrow_tracking":   (".eyebrow .lbl", "letter-spacing"),
}


def reflow_step(card, blk):
    """The rung of the block's REFLOW ladder this card's item count lands on.

    🔴 A CARD THAT IS TOO FULL SHOULD RESIZE, NOT HALT. (16 Aug 2026, EP27 C17.)
    `checklist` capped at six; the article printed ten questions and nine of ten
    would state a different method — so the card went `block:"bespoke"`, and a
    bespoke card is skipped by the schema, the trace gate and the invented-text
    gate together. A LAYOUT LIMIT TURNED ITSELF INTO A HOLE IN THE GATES. Type
    size is a measurement, not a judgement (design §11), which is the same
    reasoning that already removed the autofit halt.

    THE BLOCK DECLARES ITS OWN LADDER, in its own schema, so a block added
    tomorrow answers for itself and there is no list here to keep in sync. Each
    rung is `fit` — the SAME numeric-only channel a human uses, validated by the
    same FIT_NUM — so a reflow can move type and columns and can never introduce
    a word.

    🔒 THE FIRST RUNG RESTATES THE BLOCK'S OWN BASE VALUES, so a card small
    enough to have been fine yesterday does not move. MEASURED, not assumed: a
    six-item checklist rendered by this code and by the version before it differ
    by ZERO PIXELS at 1920x1080. That is the property that makes it safe to
    change a block every shipped episode has used.
        ⚠️ THE FILE IS NOT BYTE-IDENTICAL, and the difference matters to exactly
    one thing. The page now also STATES those values in its fit block, so
    `main()`'s existing-vs-fresh comparison sees a changed page and re-authors an
    already-built card the next time it runs over one. Same picture, new bytes —
    which is the right behaviour (the definition did change) but is worth knowing
    before it looks like a card moving on its own.
    """
    spec = (blk.get("schema") or {}).get("reflow")
    if not spec:
        return {}
    items = (card.get("content") or {}).get(spec.get("list")) or []
    steps = spec.get("steps") or []
    for step in steps:
        if len(items) <= int(step.get("upto", 0)):
            return step
    # Past the last rung the schema's own `max` has already halted; the last rung
    # is the honest answer for anything that gets this far.
    return steps[-1] if steps else {}


def fit_css(card, blk):
    """Build the fit override stylesheet. Values must be numeric.

    The reflow's choice goes in FIRST and the card's own `fit` on top of it: a
    human who has looked at the rendered page outranks a rule that has not.
    """
    fit = dict((reflow_step(card, blk).get("fit") or {}))
    fit.update(card.get("fit") or {})
    allowed = dict(FRAME_FIT)
    allowed.update({k: tuple(v) for k, v in blk["schema"].get("fit", {}).items()})
    rules = {}
    for k, v in fit.items():
        if k not in allowed:
            raise Halt(f"card {card.get('id')}: unknown fit key {k!r}. "
                       f"This card allows: {', '.join(sorted(allowed))}")
        v = str(v)
        if not FIT_NUM.match(v):
            raise Halt(f"card {card.get('id')}: fit[{k!r}] = {v!r} is not a bare number. "
                       f"fit carries measurements only, never text.")
        sel, prop = allowed[k]
        rules.setdefault(sel, []).append(f"{prop}:{v}")
    return "\n".join(f"{sel}{{{';'.join(props)}}}" for sel, props in rules.items())


RAIL_RE = re.compile(r"<!--@rail-->(.*?)<!--@endrail-->", re.S)


def apply_rail(page, card):
    """Fill the frame's rail region from card['rail'], or remove it entirely.

    The rail says WHERE IN THE ARGUMENT this card sits — "Rule 4 of 7" plus a lit
    segment. It lives in the FRAME, not in a block, so it can ride on any block
    without a template per combination (Jodie, 28 Jul 2026).

    The literal words "Rule" and "of" are in the frame FILE on purpose: that is what
    assert_no_invented_text treats as a template literal. Everything else the rail
    renders — the segment captions and the two numbers — comes from episode.json.
    """
    m = RAIL_RE.search(page)
    if not m:
        return page
    rail = card.get("rail")
    if not rail:
        return page[:m.start()] + page[m.end():]
    labels = rail.get("labels") or []
    n, of = int(rail["n"]), int(rail.get("of") or len(labels))
    if labels and len(labels) != of:
        raise Halt(f"card {card['id']}: rail says 'of {of}' but carries {len(labels)} "
                   f"labels. The rail must show every position or none of them.")
    if not (1 <= n <= of):
        raise Halt(f"card {card['id']}: rail position {n} is outside 1..{of}.")
    # A rail pointing at the wrong rung is worse than no rail: it tells the viewer a
    # confident lie about where they are. The lit label must be named by the card.
    if labels:
        lit = norm(str(labels[n - 1])).lower()
        names = norm(f"{card.get('eyebrow', '')} {card.get('headline', '')} "
                     f"{card.get('headline_display', '')}").lower()
        if lit not in names:
            raise Halt(
                f"card {card['id']}: the rail lights {labels[n - 1]!r} (position {n}) but "
                f"neither the eyebrow nor the headline mentions it. Either the position is "
                f"wrong or this card is not about that rung.")
    segs = []
    for i in range(1, of + 1):
        cls = "seg now" if i == n else ("seg done" if i < n else "seg")
        cap = f'<div class="cap">{esc(labels[i - 1])}</div>' if labels else ""
        segs.append(f'<div class="{cls}">{cap}</div>')
    body = (m.group(1).replace("%%RAIL_SEGS%%", "".join(segs))
            .replace("%%RAIL_N%%", str(n)).replace("%%RAIL_OF%%", str(of)))
    return page[:m.start()] + body + page[m.end():]


def render_card(card, blk, frame):
    content = card["content"]
    # The reflow rung this card lands on, keyed by the list it governs — so the
    # stagger override reaches expand_each in the same shape the block's own
    # `anim` section already has, rather than in a second shape it has to learn.
    step = reflow_step(card, blk)
    rspec = (blk.get("schema") or {}).get("reflow") or {}
    anim_over = ({rspec["list"]: step["anim"]}
                 if step.get("anim") and rspec.get("list") else None)
    markup = expand_each(blk["markup"], content, blk)
    markup = fill(markup, content)
    anim = expand_each(blk["anim"], content, blk, anim=True, anim_over=anim_over)

    last = max([int(d) for d in re.findall(r'"delay":(\d+)', anim)] or [500])
    page = frame
    page = page.replace("%%GENMARK%%", MARKER)
    page = page.replace("%%TITLE%%", esc(card.get("title_tag", f"PP {card['id']}")))
    page = page.replace("%%EYEBROW%%", esc(card.get("eyebrow")))
    page = page.replace("%%HEADLINE%%", esc(card.get("headline_display", card.get("headline"))))
    page = page.replace("%%BLOCK_CSS%%", blk.get("css", ""))
    page = page.replace("%%BLOCK_PRINT%%", blk.get("print", ""))
    page = page.replace("%%FIT_CSS%%", fit_css(card, blk))
    page = page.replace("%%BLOCK_MARKUP%%", markup)
    page = apply_rail(page, card)
    page = page.replace("%%BLOCK_ANIM%%", anim.rstrip().rstrip(","))
    page = page.replace("%%LOGO_DELAY%%", str(last + 450))
    page = page.replace("%%FLEX%%", "display:flex;flex-direction:column;"
                        if blk["schema"].get("flex_frame") else "")
    if "%%" in page:
        raise Halt(f"card {card['id']}: frame template left unfilled slots "
                   f"{sorted(set(re.findall('%%[A-Z_]+%%', page)))}")
    return page


# ---------------------------------------------------------------- provenance

def visible_text(page):
    """The words a viewer actually sees — tags, head, script and style removed."""
    body = re.sub(r"<head.*?</head>|<script.*?</script>|<style.*?</style>", " ",
                  page, flags=re.S)
    return norm(re.sub(r"<[^>]+>", " ", html.unescape(body))).lower()


def assert_measured_items_show_a_figure(card, blk):
    """🔴 THE OTHER HALF OF THE GUARD, AND THE ONE THAT WAS MISSING.

    🔵 IT TAKES NO PAGE, AND THAT IS WHY IT CAN RUN AT THE COMMISSION. It used to
    accept one and compute `visible_text(page)` into a variable nothing ever read —
    so it LOOKED like a render-time check and was filed with the two that genuinely
    are. It is pure episode.json, it always was, and preflight_cards calls it at
    audit_inputs on the strength of that (11 Aug 2026).

    `assert_no_invented_text` proves nothing appears that is not in the file. NOTHING
    proved the reverse — that a number the card is ABOUT reaches the screen at all.

    EP18 C9, 8 Aug 2026: the `bars` block uses {{ITEM.value}} for {{WIDTH}} only, the
    bar's LENGTH, and never draws it as text. C9's notes read "per cent profit on
    turnover" with no number in front, so the finished video showed two bars and a
    dangling phrase. `check_trace` passed, correctly — 5 and 12 both trace. It had
    verified the DATA and nobody had looked at the PICTURE.

    ⚠️ THE RULE IS PER ITEM, NOT PER FIGURE, AND THE NARROWING IS THE WHOLE POINT.
    The first version demanded that EVERY figure appear on screen, and it halted EP18's
    C3 — an episode that shipped and is right. C3 draws win counts as bar LENGTHS and
    labels them with strike rates: the measurement is the picture, the note is the
    number, and the viewer is well served. Demanding both would ban a good card.
    What cannot stand is an item that carries a measurement and shows NO figure at all:
    a bar, and a caption with a hole where the number should be.

    Which fields are measurement-only is read from the BLOCK'S OWN SCHEMA (`numeric`),
    so a block added tomorrow is covered without anyone listing it here.

    ⚠️ A FIGURE SPELLED OUT IS STILL A FIGURE (11 Aug 2026). The first version tested
    for a DIGIT, and on EP17 C3 — win counts drawn as bars, captioned "Sixteen per
    cent" / "Ten per cent" / "Five per cent" — it reported a card that shows three
    figures as showing none. That is precisely the shape the paragraph above BLESSES:
    the measurement is the picture, the note is the number. It surfaced when this
    check was wired into the commission, where a wrong halt costs three repair
    cycles rather than one look at a run log.
        THE COST OF THE WIDENING, NAMED: a caption that merely contains the word
    "one" or "hundred" as prose now counts as showing a figure, so a genuinely empty
    caption could slip through on a coincidence. That is the cheaper mistake. A guard
    that halts a good episode is the version somebody switches off (CLAUDE.md 4a),
    and the four real catches — EP14 C8, EP17 (none), EP18 C9, EP20 C5 — all still
    fire, because "lengths behind the leader", "per cent profit on turnover" and
    "variables" contain no number in any spelling.
    """
    content = card.get("content") or {}
    lists = (blk.get("schema") or {}).get("lists", {})
    # 🔴 EVERY OFFENDING ITEM, IN ONE MESSAGE. (EP21, 11 Aug 2026.)
    # This used to `raise` on the FIRST one, and that turned a bounded repair loop
    # into whack-a-mole. EP21's C9 had BOTH bars unlabelled; the writer was told only
    # about "Randwick", fixed it, resubmitted, was told about "Rosehill", and the
    # three attempts ran out on ONE CARD. The engine then halted saying — correctly —
    # that retrying would not help.
    #     EP20's C5 was the same shape and only survived because a human fixed both
    # bars by hand while looking at the one it named.
    # The rule was already written down, in _epjson_gate: "The writer gets every
    # complaint at once." A checker that reports one fault per attempt cannot be used
    # inside a loop with three attempts.
    bad = []
    for name, spec in lists.items():
        numeric = set(spec.get("numeric", []))
        if not numeric:
            continue                     # nothing here is measurement-only
        # ⚠️ "MEASUREMENT-ONLY" WAS AN ASSUMPTION ABOUT EVERY BLOCK, AND `ladder`
        # BREAKS IT. This check's whole premise — written into its own halt message —
        # is that "a list's numeric field sets the bar LENGTH only, it is never
        # rendered as text". True of `bars`, where the number reaches the screen
        # solely through the note beside it. NOT true of the ladder, whose figure IS
        # the label above its bar: 50.0 is drawn at 68px Anton and is the single
        # biggest thing on the card. Left unstated, this would have halted the ladder
        # for showing no figure while showing seven of them.
        #     READ FROM THE BLOCK'S OWN SCHEMA, like `numeric` beside it, so a block
        # added tomorrow declares its own answer instead of being listed here.
        if spec.get("shows_numeric"):
            continue
        for i, item in enumerate(content.get(name) or [], 1):
            if not isinstance(item, dict):
                continue
            measured = [item.get(k) for k in numeric if str(item.get(k) or "").strip()]
            if not measured:
                continue                 # nothing being measured, nothing to show
            shown = [v for k, v in item.items()
                     if k not in numeric and isinstance(v, str) and shows_a_figure(v)]
            if shown:
                continue
            label = item.get("label") or item.get("k") or f"{name}[{i}]"
            bad.append(f"{name}[{i}] ({label!r}), drawn as a measurement of "
                       f"{measured[0]!r}")
    if bad:
        one = len(bad) == 1
        lead = ("this item is drawn as a measurement and shows NO figure anywhere a "
                "viewer can read it" if one else
                f"these {len(bad)} items are drawn as measurements and show NO figure "
                f"anywhere a viewer can read them")
        raise Halt(
            f"card {card.get('id')}: {lead} — " + "; ".join(bad) + ". "
            "A list's numeric field sets the bar LENGTH only — it is never rendered as "
            "text — so the number reaches the screen solely through the item's other "
            "fields, and none of them has one. EP18 C9 shipped exactly this: two bars "
            'and "per cent profit on turnover" with nothing in front. Its notes became '
            '"5 per cent profit on turnover". '
            + ("" if one else "FIX THEM ALL: they are listed together on purpose, "
                              "because fixing one and resubmitting spends an attempt "
                              "and comes straight back."))


def assert_no_invented_text(page, card, frame_tpl, blk):
    """Post-hoc proof of guard 3: every visible word came from the file.

    Strip the generated page back to its visible text and check that each word
    of it appears either in a template literal or in a content value. If this
    ever fires it means a code path produced prose, which must not exist.
    """
    body = re.sub(r"<head.*?</head>|<script.*?</script>|<style.*?</style>", " ",
                  page, flags=re.S)
    visible = norm(re.sub(r"<[^>]+>", " ", html.unescape(body))).lower()
    allowed = norm(html.unescape(re.sub(r"<[^>]+>", " ",
                   frame_tpl + blk["markup"]))).lower()
    for _, v in walk_values(card["content"]):
        if isinstance(v, str):
            allowed += " " + norm(html.unescape(re.sub(r"<[^>]+>", " ", v))).lower()
    for fld in ("eyebrow", "headline_display", "headline"):
        if card.get(fld):
            allowed += " " + norm(card[fld]).lower()
    # A list's 1-based position number ({{I}}) is generated by the template, not
    # authored — the `steps` ladder prints it. It is not prose and cannot be
    # fabricated: it is bounded by the length of the list in episode.json.
    for v in (card["content"] or {}).values():
        if isinstance(v, list):
            allowed += " " + " ".join(str(i) for i in range(1, len(v) + 1))
    # The rail's captions and numbers are episode.json data exactly like content is.
    rail = card.get("rail") or {}
    for lab in (rail.get("labels") or []):
        allowed += " " + norm(str(lab)).lower()
    for k in ("n", "of"):
        if rail.get(k) is not None:
            allowed += " " + str(rail[k])
    stray = [w for w in visible.split() if w and w not in allowed]
    if stray:
        raise Halt(f"card {card['id']}: generated page contains text that is in NEITHER the "
                   f"template nor episode.json: {stray[:8]}. This is a generator bug — "
                   f"the substitution engine must never originate prose.")


# ---------------------------------------------------------------- main

def source_article_raw(ep_json, ep_dir):
    """The verbatim source article named in episode.json -> source, AS WRITTEN.

    Split out from source_article_text because a lift needs the RAW file: a
    markdown table's row structure lives entirely in its newlines, and `norm()`
    collapses them. Same lookup, one implementation, two readings — which is the
    same split `author_ebook` makes between article_blocks and article_paragraphs,
    and for the identical reason.
    """
    src = ep_json.get("source", "")
    m = re.search(r"(docs/[\w\-.]+\.md)", src)
    if not m:
        raise Halt("episode.json -> source does not name a 'Verbatim source: docs/....md' file, "
                   "so no figure can be traced. Trace-or-halt cannot be satisfied.")
    rel = m.group(1)
    for base in (os.path.dirname(os.path.dirname(os.path.abspath(ep_dir))), ep_dir):
        p = os.path.join(base, rel)
        if os.path.exists(p):
            return open(p, encoding="utf-8").read()
    raise Halt(f"source article {rel!r} named in episode.json was not found on disk")


def source_article_text(ep_json, ep_dir):
    """Find the verbatim source article named in episode.json -> source."""
    return norm(source_article_raw(ep_json, ep_dir))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("episode_json")
    ap.add_argument("out_dir")
    ap.add_argument("--only", help="comma-separated card ids")
    ap.add_argument("--force", action="store_true",
                    help="regenerate pages that already carry the generated marker")
    a = ap.parse_args()

    ep_dir = os.path.dirname(os.path.abspath(a.episode_json))
    ep = json.load(open(a.episode_json, encoding="utf-8"))
    raw_article = source_article_raw(ep, ep_dir)
    article = norm(raw_article)
    only = set(a.only.split(",")) if a.only else None

    cards = [c for c in ep.get("cards", []) if c.get("block")]
    if only:
        cards = [c for c in cards if c["id"] in only]

    # 🔴 THE LIFT RUNS FIRST, BEFORE ONE GATE LOOKS AT ONE CARD. A lifted card is
    # INCOMPLETE in episode.json on purpose — its rows are an empty slot — so a
    # schema check run before the fill would report a card with no rows, which is
    # true and useless. Filling first means every gate downstream sees the card a
    # viewer will see, and none of them needs to know a lift happened.
    lifted = apply_lifts(cards, raw_article)
    if lifted:
        print(f"lifted the data for {len(lifted)} card(s) straight out of the "
              f"capture: {', '.join(lifted)}")

    # --- guards first, for EVERY card, before one byte is written -----------
    problems, plan = [], []
    for c in cards:
        if c["block"] == "bespoke":
            continue
        try:
            blk = load_block(c["block"])
            validate(c, blk)
            problems += check_job(c)
            problems += check_trace(c, article)
            problems += check_dead_trace(c)
            problems += check_converted_odds(c)
            plan.append((c, blk))
        except Halt as e:
            problems.append(str(e))
    problems += check_mix(cards)
    if problems:
        print(f"AUTHORING HALTED — {len(problems)} problem(s):", file=sys.stderr)
        for p in problems:
            print(f"  ✗ {p}", file=sys.stderr)
        sys.exit(2)

    os.makedirs(a.out_dir, exist_ok=True)
    wrote, redone, skipped = [], [], []
    for c, blk in plan:
        frame_tpl = load_frame(c.get("layout", "fullscreen"))
        page = render_card(c, blk, frame_tpl)
        assert_no_invented_text(page, c, frame_tpl, blk)
        assert_measured_items_show_a_figure(c, blk)
        out = os.path.join(a.out_dir, c["page"])
        if os.path.exists(out):
            existing = open(out, encoding="utf-8").read()
            # A HAND-AUTHORED PAGE IS NEVER TOUCHED, not even with --force.
            # This check comes first on purpose: bespoke pages are the one thing
            # a blanket re-author would destroy.
            if MARKER not in existing:
                skipped.append((c["id"], c["page"], "hand-authored (no generated marker)"))
                continue
            # 🔴 THE --force TRAP, CLOSED. This used to read "already generated —
            # pass --force to redo", and the ENGINE NEVER PASSES --force. So
            # changing episode.json and clearing the flag re-checked the STALE
            # HTML and returned a byte-identical halt.
            #
            #     A CORRECT FIX LOOKED LIKE A FAILED ONE, TWICE.
            #
            # It broke nothing. It made the truth invisible — and the natural
            # next move is to undo a change that was right, or hunt a second
            # cause that is not there. On EP16 a layout fix moved a box from
            # (204,838) to (110,787) and NOTHING SHOWED IT, because the page on
            # disk was never rewritten.
            #
            # THE FIX IS DERIVED, NOT A LIST AND NOT A TIMESTAMP: the freshly
            # rendered page is already in hand, so COMPARE IT. If it differs, the
            # card's definition changed and the page is rewritten. If it is
            # identical, there was nothing to do anyway. Nothing to keep in sync,
            # nothing anyone must remember to bump, and it cannot go stale —
            # because the comparison IS the definition. (CLAUDE.md fault #7.)
            if existing == page and not a.force:
                skipped.append((c["id"], c["page"],
                                "unchanged — episode.json still says the same thing"))
                continue
            redone.append(c["page"])
        open(out, "w", encoding="utf-8", newline="\n").write(page)
        wrote.append(c["page"])

    for c in cards:
        if c["block"] == "bespoke":
            skipped.append((c["id"], c.get("page", "?"), "block:bespoke — hand-authored by design"))

    # SAY WHICH PAGES WERE RE-AUTHORED, not just how many were written. The whole
    # cost of the --force trap was that a regeneration and a no-op looked
    # identical from the outside.
    print(f"authored {len(wrote)} card page(s) into {a.out_dir}"
          + (f" ({len(redone)} REDONE because the card changed)" if redone else ""))
    for p in wrote:
        print(f"  {'~' if p in redone else '+'} {p}"
              + ("  (re-authored — its definition changed)" if p in redone else ""))
    for cid, page, why in skipped:
        print(f"  · {cid} {page} — left alone: {why}")
    # Untidy-but-harmless citations go in the RUN LOG, never in a gate — see the note
    # in preflight_cards.preflight_cards() for why they are not warnings.
    for c in cards:
        for s in check_stray_trace(c):
            print(f"  · {s}")


if __name__ == "__main__":
    try:
        main()
    except Halt as e:
        print(f"AUTHORING HALTED — {e}", file=sys.stderr)
        sys.exit(2)
