#!/usr/bin/env python3
"""author_cards.py — author motion-graphic card pages by PURE SUBSTITUTION.

    python author_cards.py <episode.json> <out_dir> [--only C1,C2] [--force]

THE ONE PROPERTY THIS SCRIPT MUST HAVE
--------------------------------------
It is structurally incapable of emitting visible text that is not already in
`episode.json`. There is no LLM in it, no inference, no defaulting-to-a-phrase,
no string built from anything but (a) template literals and (b) values copied
out of `cards[].content`. If a value is missing it HALTS; it never fills a gap.

That is guard 3 of DESIGN-self-authoring-build.md §6, and it is a capability the
program does not have rather than a rule it is asked to follow.

THE OTHER TWO GUARDS
--------------------
1. SCHEMA VALIDATION before anything renders. Unknown block, unknown key for
   that block, missing required key, wrong list length -> halt naming card+key.
2. TRACE-OR-HALT. Any content value containing a digit needs a `trace` entry,
   that entry must be a literal substring of the source article, AND every
   digit-run in the value must appear inside the traced sentence. The second
   half is what catches EP11's C7: the traced sentence was real, but it did not
   contain the "2nd"/"3rd" placings that had been inferred from listing order.

EXPLICIT null RENDERS AN EMPTY SLOT. A MISSING KEY HALTS.
That is the EP12 `_placeholder` lesson: explicit null says a human decided this
is empty; absence says nobody decided.

NEVER OVERWRITE HAND-AUTHORED WORK. Generated pages carry the marker comment
below. A page without it is treated as hand-authored and left alone; `block:
"bespoke"` is never generated at all.
"""
import argparse
import html
import json
import os
import re
import sys
import unicodedata

for _s in (sys.stdout, sys.stderr):       # the Windows console is cp1252
    try:
        _s.reconfigure(encoding="utf-8")
    except Exception:                     # noqa: BLE001
        pass

HERE = os.path.dirname(os.path.abspath(__file__))
CARDS_DIR = os.path.join(os.path.dirname(HERE), "assets", "cards")

MARKER = "<!-- PP-GENERATED by author_cards.py — DO NOT HAND-EDIT. "\
         "To change this card, change episode.json; to take it over by hand, "\
         "set block:\"bespoke\" and delete this line. -->"

# Inline markup a content value is allowed to carry. Everything else is escaped,
# so episode.json cannot inject script, style or structure into a card.
INLINE_OK = ("<b>", "</b>", "<br>")


class Halt(Exception):
    """A build-stopping problem, phrased for a human."""


# ---------------------------------------------------------------- templates

SECTIONS = ("schema", "css", "print", "markup", "anim")


def _sections(text):
    """Split a block file on its section markers.

    A marker is `<!--@name-->` on its own line, or `<!--@name` opening a
    multi-line HTML comment (the schema is JSON, so it is written that way and
    closed by a line that is just `-->`).
    """
    out, name, buf = {}, None, []
    for line in text.splitlines():
        m = re.match(r"\s*<!--@(\w+)\s*(?:-->)?\s*$", line)
        if m and m.group(1) in SECTIONS:
            if name:
                out[name] = "\n".join(buf).strip("\n")
            name, buf = m.group(1), []
            continue
        if line.strip() == "-->" and name == "schema":
            continue
        if name:
            buf.append(line)
    if name:
        out[name] = "\n".join(buf).strip("\n")
    return out


def load_block(block):
    path = os.path.join(CARDS_DIR, "blocks", block + ".html")
    if not os.path.exists(path):
        have = sorted(f[:-5] for f in os.listdir(os.path.join(CARDS_DIR, "blocks"))
                      if f.endswith(".html"))
        raise Halt(f"unknown block {block!r}. Known blocks: {', '.join(have)}")
    s = _sections(open(path, encoding="utf-8").read())
    for need in ("schema", "markup", "anim"):
        if need not in s:
            raise Halt(f"block {block!r} template is missing its @{need} section")
    s["schema"] = json.loads(s["schema"])
    return s


def load_frame(layout):
    path = os.path.join(CARDS_DIR, f"frame-{ 'panel' if layout == 'panel-push' else 'fullscreen' }.html")
    if not os.path.exists(path):
        raise Halt(f"no frame template for layout {layout!r} (expected {path})")
    return open(path, encoding="utf-8").read()


# ---------------------------------------------------------------- normalising

_QUOTES = {"‘": "'", "’": "'", "“": '"', "”": '"',
           "–": "-", "—": "-", "−": "-", " ": " "}


def norm(s):
    """Normalise for the TRACE comparison only — never for what is rendered.

    Whitespace is collapsed and typographic quotes/dashes are folded to ASCII.
    The design said "whitespace only"; quotes had to be added because the cards
    carry curly quotes and the source articles carry straight ones, so a
    whitespace-only comparison failed every single trace. Widening this further
    (case, punctuation, stemming) would start hiding real mismatches.
    """
    s = unicodedata.normalize("NFKC", s)
    s = "".join(_QUOTES.get(ch, ch) for ch in s)
    return re.sub(r"\s+", " ", s).strip()


def digit_runs(s):
    return re.findall(r"\d+(?:\.\d+)?", s)


# ---------------------------------------------------------------- validation

def validate(card, blk):
    """Halt on anything the schema does not describe. Returns nothing."""
    cid = card.get("id", "<no id>")
    schema = blk["schema"]
    content = card.get("content")
    if content is None:
        raise Halt(f"card {cid}: block {card['block']!r} needs a content{{}} object and there is none")
    if not isinstance(content, dict):
        raise Halt(f"card {cid}: content must be an object, got {type(content).__name__}")

    required = schema.get("required", [])
    optional = schema.get("optional", [])
    lists = schema.get("lists", {})
    known = set(required) | set(optional) | set(lists)

    for k in content:
        if k not in known:
            raise Halt(f"card {cid}: unknown key {k!r} for block {card['block']!r}. "
                       f"This block accepts: {', '.join(sorted(known))}")
    # EVERY key the block declares must be PRESENT. Required keys must also be
    # non-null. An optional key may be null — that renders an empty slot, and it
    # records that a human decided it is empty. Absence records nothing, so it halts.
    for k in required + optional:
        if k not in content:
            kind = "required" if k in required else "optional"
            raise Halt(f"card {cid}: MISSING {kind} key {k!r} for block {card['block']!r}. "
                       f"If the value is deliberately empty write null — a missing key halts "
                       f"on purpose, because absence means nobody decided.")
    for k in required:
        if content[k] is None:
            raise Halt(f"card {cid}: key {k!r} is null, but block {card['block']!r} requires "
                       f"a value for it.")
    for name, spec in lists.items():
        if name not in content:
            if name in required:
                raise Halt(f"card {cid}: MISSING required list {name!r}")
            continue
        items = content[name]
        if not isinstance(items, list):
            raise Halt(f"card {cid}: {name!r} must be a list")
        lo, hi = spec.get("min", 1), spec.get("max", 99)
        if not (lo <= len(items) <= hi):
            raise Halt(f"card {cid}: {name!r} has {len(items)} items; block {card['block']!r} "
                       f"takes between {lo} and {hi}")
        fields = spec.get("fields")
        for i, it in enumerate(items, 1):
            if fields is None:
                if it is not None and not isinstance(it, str):
                    raise Halt(f"card {cid}: {name}[{i}] must be a string or null")
            else:
                if not isinstance(it, dict):
                    raise Halt(f"card {cid}: {name}[{i}] must be an object with {fields}")
                for k in it:
                    if k not in fields:
                        raise Halt(f"card {cid}: {name}[{i}] has unknown field {k!r}; allowed: {fields}")
                for k in fields:
                    if k not in it:
                        raise Halt(f"card {cid}: {name}[{i}] is MISSING field {k!r}. "
                                   f"Write null for a deliberately empty slot.")
                # Fields that select a style variant are a closed set, so a content
                # value can never invent a CSS class.
                for k, allowed_vals in spec.get("enum", {}).items():
                    if it.get(k) not in allowed_vals:
                        raise Halt(f"card {cid}: {name}[{i}].{k} = {it.get(k)!r} is not one of "
                                   f"{allowed_vals}. This field picks a style variant, "
                                   f"so it is a closed set.")
                # Fields that drive a measurement must be bare numbers.
                for k in spec.get("numeric", []):
                    if not re.match(r"^\d+(\.\d+)?$", str(it.get(k, ""))):
                        raise Halt(f"card {cid}: {name}[{i}].{k} = {it.get(k)!r} must be a bare "
                                   f"number — it sets a bar length, not a caption.")


def walk_values(content):
    """Yield (dotted_key, value) for every leaf string in content."""
    for k, v in content.items():
        if isinstance(v, list):
            for i, it in enumerate(v, 1):
                if isinstance(it, dict):
                    for kk, vv in it.items():
                        yield f"{k}[{i}].{kk}", vv
                else:
                    yield f"{k}[{i}]", it
        else:
            yield k, v


JOBS = ("orient", "locate", "relate", "anchor")

# R3a — a job is a CLAIM, and a claim needs a check.
#
# Assertion fell from 54% to 20% overnight and the pictures were IDENTICAL: the
# cards had been RELABELLED, not changed. A `statement` block declaring itself
# `relate` makes the metric improve while the episode does not — which is the
# oldest way there is to pass a gate without doing the work. So the declared job
# must be consistent with the block that actually renders: a card cannot claim to
# relate two things using a block that can only assert one.
JOB_BLOCKS = {
    # `statement` is here on the standard's OWN wording: R3 counts pure assertion as
    # "anchor, or a bare statement". A bare statement IS an assertion, so it must
    # declare `anchor` and be counted against the 40% cap — not hide under `relate`.
    "anchor": {"stat", "price", "statement"},
    # `slate` and `checklist` CONFIRMED for relate by Jodie, 29 Jul 2026: "four causes
    # pointing at one outcome IS a relationship, and C3's two lists of what stands
    # between ability and result is the same shape." SUBJECT TO THE LIST QUALIFIER
    # below — a list earns `relate` only when it shows what the items connect TO.
    "relate": {"compare", "steps", "bars", "ratio", "slate", "checklist"},
    "orient": {"steps", "slate"},
    # `locate` is the rail modifier — it rides on any block, so it constrains none.
    "locate": None,
}

# Blocks that merely ENUMERATE. They can relate — but only by naming the thing the
# items connect to (see the list qualifier in check_job).
LIST_BLOCKS = {"checklist", "slate"}

# R3 IS MEASURED ON THE BLOCK, NEVER ON THE DECLARED JOB. Assertion "fell" from 54%
# to 20% overnight while the pictures stayed identical, because the cards had been
# relabelled. A metric you can move by editing a label is not a metric.
ASSERTION_BLOCKS = {"stat", "price", "statement"}
MAX_ASSERTION = 0.40


def check_mix(cards):
    """R3: at most 40% of content cards may be pure assertion, counted BY BLOCK."""
    content = [c for c in cards if c.get("block") and c.get("page")]
    if not content:
        return []
    hard = [c["id"] for c in content if c["block"] in ASSERTION_BLOCKS]
    share = len(hard) / len(content)
    if share > MAX_ASSERTION:
        return [f"EPISODE MIX: {len(hard)} of {len(content)} content cards are pure assertion "
                f"({share*100:.0f}%), over the {MAX_ASSERTION*100:.0f}% cap "
                f"(pp-visual-standard R3). The assertion cards are {hard}. Measured on the "
                f"BLOCK, not the declared job — relabelling does not change a picture."]
    return []


def check_job(card):
    """R2 of the visual standard: EVERY CARD DECLARES ITS JOB. No job, no build.

    The four jobs are orient / locate / relate / anchor, and they are the answer to
    "what is this card FOR". A card that does none of them is decoration — and
    decoration is not free: the coherence principle says it makes the episode
    WORSE, not merely no better. The vocabulary is owned by the pp-visual-standard
    skill; this is only the gate.

    It is a closed list on purpose, exactly like `ebook.departures` and the block
    names: a free-text field would let "job": "explain" through, and the whole
    point is that the author must pick one of four and live with it.
    """
    j = card.get("job")
    if j is None:
        return [f"card {card.get('id', '?')}: MISSING 'job'. Every card must declare what it is "
                f"FOR — one of {', '.join(JOBS)} (pp-visual-standard R2). A card that does none "
                f"of the four is decoration and must not be built."]
    if j not in JOBS:
        return [f"card {card.get('id', '?')}: job {j!r} is not one of {', '.join(JOBS)}. "
                f"This is a closed vocabulary, not free text."]
    allowed = JOB_BLOCKS.get(j)
    blk = card.get("block")
    if allowed is not None and blk not in allowed and blk != "bespoke":
        return [f"card {card.get('id', '?')}: declares job {j!r} but uses block {blk!r}. "
                f"{j!r} needs one of {sorted(allowed)} (pp-visual-standard R3a). A job is a "
                f"CLAIM about what the card does — relabelling a block does not change the "
                f"picture, and R3 is measured on the BLOCK for exactly that reason."]
    # THE LIST QUALIFIER (Jodie, 29 Jul 2026). A list block earns `relate` only when it
    # shows what the items connect TO. "These four things set the track bias" is a
    # relationship — many causes, one outcome. A bare enumeration with no subject is
    # assertion wearing a list's clothes, and it must declare `anchor` and count
    # against the 40% cap instead. The connection has to be NAMED, so the claim is
    # explicit and reviewable rather than implied by the choice of block.
    if j == "relate" and blk in LIST_BLOCKS and not str(card.get("relates_to") or "").strip():
        return [f"card {card.get('id', '?')}: a {blk!r} claiming job 'relate' must name what "
                f"its items connect to, in 'relates_to' (pp-visual-standard R3a, the list "
                f"qualifier). Many causes pointing at ONE outcome is a relationship; a bare "
                f"enumeration is assertion wearing a list's clothes — declare 'anchor' for "
                f"that and let it count against the 40% cap."]
    return []


def check_trace(card, article_norm):
    """Trace-or-halt. Any value with a digit must be traceable to the article."""
    cid = card.get("id", "<no id>")
    trace = card.get("trace") or {}
    problems = []
    # The headline and the eyebrow are figures too. EP12 C3's headline IS the
    # claim ("90 Days Is Not 180 Days") and EP11 C4's eyebrow carries a date;
    # checking only content{} would leave the largest text on the card untraced.
    extra = [("headline", card.get("headline_display") or card.get("headline")),
             ("eyebrow", card.get("eyebrow"))]
    # The rail prints "Rule N of M". M is a claim about the article — how many rules
    # there are — so it is a figure and must trace like any other. N is not a claim
    # about the world, it is a pointer into the list this very card displays, so it is
    # bounds-checked and cross-checked against the eyebrow in apply_rail() instead.
    rail = card.get("rail") or {}
    if rail.get("of") is not None:
        extra.append(("rail", str(rail["of"])))
    for key, val in list(walk_values(card["content"])) + extra:
        if not isinstance(val, str) or not re.search(r"\d", val):
            continue
        base = key.split("[")[0]
        sentence = trace.get(key, trace.get(base))
        if sentence is None:
            problems.append(f"{cid}.{key} = {val!r} carries a figure and has NO trace entry. "
                            f"Add trace[{base!r}] quoting the source sentence.")
            continue
        sn = norm(sentence)
        if sn not in article_norm:
            problems.append(f"{cid}.trace[{base!r}] is not a literal substring of the source "
                            f"article: {sentence!r}")
            continue
        missing = [d for d in digit_runs(norm(val)) if d not in sn]
        if missing:
            problems.append(
                f"{cid}.{key} = {val!r} shows figure(s) {missing} that do NOT appear in its own "
                f"traced sentence. The sentence is real but it does not say this. "
                f"(This is the EP11 C7 failure: placings inferred from listing order.)")
    return problems


# ---------------------------------------------------------------- rendering

def esc(v):
    """Escape a content value, then re-admit the small inline whitelist.

    This is the choke point that makes fabrication structurally impossible:
    every visible character in a generated card comes through here from
    episode.json, or is a literal in the template file.
    """
    if v is None:
        return ""
    if not isinstance(v, str):
        raise Halt(f"content values must be strings or null, got {type(v).__name__}: {v!r}")
    out = html.escape(v, quote=False)
    for tag in INLINE_OK:
        out = out.replace(html.escape(tag, quote=False), tag)
    return out


def expand_each(tpl, content, blk, anim=False):
    """Expand <!--@each name--> ... <!--@endeach--> regions.

    {{ITEM}} / {{ITEM.field}} — the value, escaped
    {{I}}                     — 1-based index (element ids, never visible text)
    {{DELAY}}                 — stagger delay from the block's declared base+step
    {{WIDTH}}                 — a length in px PROPORTIONAL to the item's numeric
                                field, so a bar cannot misstate the ratio it draws
    """
    lists = blk["schema"].get("lists", {})
    anim_spec = blk["schema"].get("anim", {}) if anim else {}

    def one(m):
        name, body = m.group(1), m.group(2)
        items = content.get(name)
        if items is None:
            return ""
        spec = lists.get(name, {})
        step = anim_spec.get(name, {})
        scale = spec.get("scale")
        span = 0.0
        if scale:
            vals = [float(it[scale["field"]]) for it in items]
            span = max(vals) or 1.0
        chunks = []
        for i, it in enumerate(items, 1):
            piece = body
            if isinstance(it, dict):
                for k, v in it.items():
                    piece = piece.replace("{{ITEM." + k + "}}", esc(v))
                if scale:
                    w = round(float(it[scale["field"]]) / span * scale["span"])
                    piece = piece.replace("{{WIDTH}}", str(w))
            else:
                piece = piece.replace("{{ITEM}}", esc(it))
            piece = piece.replace("{{I}}", str(i))
            if step:
                piece = piece.replace("{{DELAY}}", str(step["base"] + (i - 1) * step["step"]))
                if "base2" in step:
                    piece = piece.replace("{{DELAY2}}",
                                          str(step["base2"] + (i - 1) * step["step2"]))
            chunks.append(piece)
        return "".join(chunks)
    return re.sub(r"<!--@each (\w+)-->(.*?)<!--@endeach-->", one, tpl, flags=re.S)


def fill(tpl, content):
    """Replace {{key}} with the escaped content value. Unresolved token = halt."""
    def one(m):
        k = m.group(1)
        if k not in content:
            raise Halt(f"template wants {{{{{k}}}}} but content has no key {k!r}")
        return esc(content[k])
    out = re.sub(r"\{\{(\w+)\}\}", one, tpl)
    leftover = re.findall(r"\{\{[\w.]+\}\}", out)
    if leftover:
        raise Halt(f"template left unresolved placeholders: {sorted(set(leftover))}")
    return out


FIT_NUM = re.compile(r"^-?\d+(\.\d+)?(px|em|%)?$")

# Fit keys shared by both frames. Numeric only — no text can enter through fit.
FRAME_FIT = {
    "headline_size":      (".hl", "font-size"),
    "headline_leading":   (".hl", "line-height"),
    "headline_top":       (".hl", "margin-top"),
    "eyebrow_size":       (".eyebrow .lbl", "font-size"),
    "eyebrow_tracking":   (".eyebrow .lbl", "letter-spacing"),
}


def fit_css(card, blk):
    """Build the fit override stylesheet. Values must be numeric."""
    fit = card.get("fit") or {}
    allowed = dict(FRAME_FIT)
    allowed.update({k: tuple(v) for k, v in blk["schema"].get("fit", {}).items()})
    rules = {}
    for k, v in fit.items():
        if k not in allowed:
            raise Halt(f"card {card.get('id')}: unknown fit key {k!r}. "
                       f"This card allows: {', '.join(sorted(allowed))}")
        v = str(v)
        if not FIT_NUM.match(v):
            raise Halt(f"card {card.get('id')}: fit[{k!r}] = {v!r} is not a bare number. "
                       f"fit carries measurements only, never text.")
        sel, prop = allowed[k]
        rules.setdefault(sel, []).append(f"{prop}:{v}")
    return "\n".join(f"{sel}{{{';'.join(props)}}}" for sel, props in rules.items())


RAIL_RE = re.compile(r"<!--@rail-->(.*?)<!--@endrail-->", re.S)


def apply_rail(page, card):
    """Fill the frame's rail region from card['rail'], or remove it entirely.

    The rail says WHERE IN THE ARGUMENT this card sits — "Rule 4 of 7" plus a lit
    segment. It lives in the FRAME, not in a block, so it can ride on any block
    without a template per combination (Jodie, 28 Jul 2026).

    The literal words "Rule" and "of" are in the frame FILE on purpose: that is what
    assert_no_invented_text treats as a template literal. Everything else the rail
    renders — the segment captions and the two numbers — comes from episode.json.
    """
    m = RAIL_RE.search(page)
    if not m:
        return page
    rail = card.get("rail")
    if not rail:
        return page[:m.start()] + page[m.end():]
    labels = rail.get("labels") or []
    n, of = int(rail["n"]), int(rail.get("of") or len(labels))
    if labels and len(labels) != of:
        raise Halt(f"card {card['id']}: rail says 'of {of}' but carries {len(labels)} "
                   f"labels. The rail must show every position or none of them.")
    if not (1 <= n <= of):
        raise Halt(f"card {card['id']}: rail position {n} is outside 1..{of}.")
    # A rail pointing at the wrong rung is worse than no rail: it tells the viewer a
    # confident lie about where they are. The lit label must be named by the card.
    if labels:
        lit = norm(str(labels[n - 1])).lower()
        names = norm(f"{card.get('eyebrow', '')} {card.get('headline', '')} "
                     f"{card.get('headline_display', '')}").lower()
        if lit not in names:
            raise Halt(
                f"card {card['id']}: the rail lights {labels[n - 1]!r} (position {n}) but "
                f"neither the eyebrow nor the headline mentions it. Either the position is "
                f"wrong or this card is not about that rung.")
    segs = []
    for i in range(1, of + 1):
        cls = "seg now" if i == n else ("seg done" if i < n else "seg")
        cap = f'<div class="cap">{esc(labels[i - 1])}</div>' if labels else ""
        segs.append(f'<div class="{cls}">{cap}</div>')
    body = (m.group(1).replace("%%RAIL_SEGS%%", "".join(segs))
            .replace("%%RAIL_N%%", str(n)).replace("%%RAIL_OF%%", str(of)))
    return page[:m.start()] + body + page[m.end():]


def render_card(card, blk, frame):
    content = card["content"]
    markup = expand_each(blk["markup"], content, blk)
    markup = fill(markup, content)
    anim = expand_each(blk["anim"], content, blk, anim=True)

    last = max([int(d) for d in re.findall(r'"delay":(\d+)', anim)] or [500])
    page = frame
    page = page.replace("%%GENMARK%%", MARKER)
    page = page.replace("%%TITLE%%", esc(card.get("title_tag", f"PP {card['id']}")))
    page = page.replace("%%EYEBROW%%", esc(card.get("eyebrow")))
    page = page.replace("%%HEADLINE%%", esc(card.get("headline_display", card.get("headline"))))
    page = page.replace("%%BLOCK_CSS%%", blk.get("css", ""))
    page = page.replace("%%BLOCK_PRINT%%", blk.get("print", ""))
    page = page.replace("%%FIT_CSS%%", fit_css(card, blk))
    page = page.replace("%%BLOCK_MARKUP%%", markup)
    page = apply_rail(page, card)
    page = page.replace("%%BLOCK_ANIM%%", anim.rstrip().rstrip(","))
    page = page.replace("%%LOGO_DELAY%%", str(last + 450))
    page = page.replace("%%FLEX%%", "display:flex;flex-direction:column;"
                        if blk["schema"].get("flex_frame") else "")
    if "%%" in page:
        raise Halt(f"card {card['id']}: frame template left unfilled slots "
                   f"{sorted(set(re.findall('%%[A-Z_]+%%', page)))}")
    return page


# ---------------------------------------------------------------- provenance

def assert_no_invented_text(page, card, frame_tpl, blk):
    """Post-hoc proof of guard 3: every visible word came from the file.

    Strip the generated page back to its visible text and check that each word
    of it appears either in a template literal or in a content value. If this
    ever fires it means a code path produced prose, which must not exist.
    """
    body = re.sub(r"<head.*?</head>|<script.*?</script>|<style.*?</style>", " ",
                  page, flags=re.S)
    visible = norm(re.sub(r"<[^>]+>", " ", html.unescape(body))).lower()
    allowed = norm(html.unescape(re.sub(r"<[^>]+>", " ",
                   frame_tpl + blk["markup"]))).lower()
    for _, v in walk_values(card["content"]):
        if isinstance(v, str):
            allowed += " " + norm(html.unescape(re.sub(r"<[^>]+>", " ", v))).lower()
    for fld in ("eyebrow", "headline_display", "headline"):
        if card.get(fld):
            allowed += " " + norm(card[fld]).lower()
    # A list's 1-based position number ({{I}}) is generated by the template, not
    # authored — the `steps` ladder prints it. It is not prose and cannot be
    # fabricated: it is bounded by the length of the list in episode.json.
    for v in (card["content"] or {}).values():
        if isinstance(v, list):
            allowed += " " + " ".join(str(i) for i in range(1, len(v) + 1))
    # The rail's captions and numbers are episode.json data exactly like content is.
    rail = card.get("rail") or {}
    for lab in (rail.get("labels") or []):
        allowed += " " + norm(str(lab)).lower()
    for k in ("n", "of"):
        if rail.get(k) is not None:
            allowed += " " + str(rail[k])
    stray = [w for w in visible.split() if w and w not in allowed]
    if stray:
        raise Halt(f"card {card['id']}: generated page contains text that is in NEITHER the "
                   f"template nor episode.json: {stray[:8]}. This is a generator bug — "
                   f"the substitution engine must never originate prose.")


# ---------------------------------------------------------------- main

def source_article_text(ep_json, ep_dir):
    """Find the verbatim source article named in episode.json -> source."""
    src = ep_json.get("source", "")
    m = re.search(r"(docs/[\w\-.]+\.md)", src)
    if not m:
        raise Halt("episode.json -> source does not name a 'Verbatim source: docs/....md' file, "
                   "so no figure can be traced. Trace-or-halt cannot be satisfied.")
    rel = m.group(1)
    for base in (os.path.dirname(os.path.dirname(os.path.abspath(ep_dir))), ep_dir):
        p = os.path.join(base, rel)
        if os.path.exists(p):
            return norm(open(p, encoding="utf-8").read())
    raise Halt(f"source article {rel!r} named in episode.json was not found on disk")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("episode_json")
    ap.add_argument("out_dir")
    ap.add_argument("--only", help="comma-separated card ids")
    ap.add_argument("--force", action="store_true",
                    help="regenerate pages that already carry the generated marker")
    a = ap.parse_args()

    ep_dir = os.path.dirname(os.path.abspath(a.episode_json))
    ep = json.load(open(a.episode_json, encoding="utf-8"))
    article = source_article_text(ep, ep_dir)
    only = set(a.only.split(",")) if a.only else None

    cards = [c for c in ep.get("cards", []) if c.get("block")]
    if only:
        cards = [c for c in cards if c["id"] in only]

    # --- guards first, for EVERY card, before one byte is written -----------
    problems, plan = [], []
    for c in cards:
        if c["block"] == "bespoke":
            continue
        try:
            blk = load_block(c["block"])
            validate(c, blk)
            problems += check_job(c)
            problems += check_trace(c, article)
            plan.append((c, blk))
        except Halt as e:
            problems.append(str(e))
    problems += check_mix(cards)
    if problems:
        print(f"AUTHORING HALTED — {len(problems)} problem(s):", file=sys.stderr)
        for p in problems:
            print(f"  ✗ {p}", file=sys.stderr)
        sys.exit(2)

    os.makedirs(a.out_dir, exist_ok=True)
    wrote, redone, skipped = [], [], []
    for c, blk in plan:
        frame_tpl = load_frame(c.get("layout", "fullscreen"))
        page = render_card(c, blk, frame_tpl)
        assert_no_invented_text(page, c, frame_tpl, blk)
        out = os.path.join(a.out_dir, c["page"])
        if os.path.exists(out):
            existing = open(out, encoding="utf-8").read()
            # A HAND-AUTHORED PAGE IS NEVER TOUCHED, not even with --force.
            # This check comes first on purpose: bespoke pages are the one thing
            # a blanket re-author would destroy.
            if MARKER not in existing:
                skipped.append((c["id"], c["page"], "hand-authored (no generated marker)"))
                continue
            # 🔴 THE --force TRAP, CLOSED. This used to read "already generated —
            # pass --force to redo", and the ENGINE NEVER PASSES --force. So
            # changing episode.json and clearing the flag re-checked the STALE
            # HTML and returned a byte-identical halt.
            #
            #     A CORRECT FIX LOOKED LIKE A FAILED ONE, TWICE.
            #
            # It broke nothing. It made the truth invisible — and the natural
            # next move is to undo a change that was right, or hunt a second
            # cause that is not there. On EP16 a layout fix moved a box from
            # (204,838) to (110,787) and NOTHING SHOWED IT, because the page on
            # disk was never rewritten.
            #
            # THE FIX IS DERIVED, NOT A LIST AND NOT A TIMESTAMP: the freshly
            # rendered page is already in hand, so COMPARE IT. If it differs, the
            # card's definition changed and the page is rewritten. If it is
            # identical, there was nothing to do anyway. Nothing to keep in sync,
            # nothing anyone must remember to bump, and it cannot go stale —
            # because the comparison IS the definition. (CLAUDE.md fault #7.)
            if existing == page and not a.force:
                skipped.append((c["id"], c["page"],
                                "unchanged — episode.json still says the same thing"))
                continue
            redone.append(c["page"])
        open(out, "w", encoding="utf-8", newline="\n").write(page)
        wrote.append(c["page"])

    for c in cards:
        if c["block"] == "bespoke":
            skipped.append((c["id"], c.get("page", "?"), "block:bespoke — hand-authored by design"))

    # SAY WHICH PAGES WERE RE-AUTHORED, not just how many were written. The whole
    # cost of the --force trap was that a regeneration and a no-op looked
    # identical from the outside.
    print(f"authored {len(wrote)} card page(s) into {a.out_dir}"
          + (f" ({len(redone)} REDONE because the card changed)" if redone else ""))
    for p in wrote:
        print(f"  {'~' if p in redone else '+'} {p}"
              + ("  (re-authored — its definition changed)" if p in redone else ""))
    for cid, page, why in skipped:
        print(f"  · {cid} {page} — left alone: {why}")


if __name__ == "__main__":
    try:
        main()
    except Halt as e:
        print(f"AUTHORING HALTED — {e}", file=sys.stderr)
        sys.exit(2)
